### ISSUE TITLE
Can't sign into Apple ID

### ISSUE THREAD

**Issue by dmorr041** [XcodesOrg/XcodesApp#331]
**Describe the bug**
Install Xcodes via `brew install --cask xcodes`
Open XCodes
Attempt to install Xcodes 14.1 (latest) - get error message that I need to sign into Apple ID first
Sign into AppleID
Get 2FA message, enter code correctly via both text message and apple device code
Get error code "412" trying to sign in, told to report as a bug, so here I am

**To Reproduce**
Steps to reproduce the behavior: See above

**Expected behavior**
Successful 2FA using either text messaged code or apple device code

**Screenshots**
<img width="912" alt="Screen Shot 2022-12-04 at 3 54 24 PM" src="https://user-images.githubusercontent.com/25493988/205517725-d1bcab9e-ef35-4274-86ba-5af834467a9d.png">

**Version**
 - OS: MacOS Monterey 12.5
 - Xcodes: 1.9.0 (17)

**Comment by EvgenijIvanov** [comment]
I have same error ...
OS: MacOS Monterey 12.6.1
Xcodes: 1.9.0
![image](https://user-images.githubusercontent.com/23220588/210439148-83dab6bb-40d5-445c-9844-2615bcae8cdb.png)

**Comment by AbstractionsAs** [comment]
Me too

**Comment by dazbrooke** [comment]
Same behaviour for me Xcodes 1.9.0 and MacOS 12.6.2
![Screenshot 2023-01-17 at 17 17 24](https://user-images.githubusercontent.com/122878600/212967357-ad4293da-d19f-4dca-9b1b-747f1242fd00.png)

**Comment by pavlo-kapinos** [comment]
Had the same issue, managed to sign in without the problem by using another account.

**Comment by stephengeorge8** [comment]
found solution: go to apple.developer.com and then log in. it made me sign an agreement. after i did that, i was able to sign into xcodes w appleid

**Comment by chengziorange** [comment]
> apple.developer.com

it is developer.apple.com

**Comment by chengziorange** [comment]
> found solution: go to apple.developer.com and then log in. it made me sign an agreement. after i did that, i was able to sign into xcodes w appleid

it is developer.apple.com
