### ISSUE TITLE
Can't login with Apple ID secured using 'Physical Security Key'

### ISSUE THREAD

**Issue by hacik81** [XcodesOrg/XcodesApp#411]
**Describe the bug**
Trying to login with my Apple ID I'm getting error presented on screenshot. My Apple account is secured with a physical security key.

**Screenshots**

![Zrzut ekranu 2023-08-6 o 18 30 57](https://github.com/XcodesOrg/XcodesApp/assets/43092885/4c94c58f-b6f6-4844-a62c-db40375099f6)

**Version**
 - OS: 13.5
 - Xcodes: 1.10.0

**Comment by Qormix** [comment]
Same issue. I tried using an App-Specific password as a work-around, but was not successful.
