### ISSUE TITLE
Received an unexpected status code: 412

### ISSUE THREAD

**Issue by DeepSeaLemon** [XcodesOrg/XcodesApp#424]
**Describe the bug**
I logged in with my Apple ID, but the verification failed.
Received an unexpected status code: 412. If you continue to have problems, please submit a bug report in the Help menu.

**To Reproduce**

**Expected behavior**
Able to log in and use normally

**Screenshots**
![image](https://github.com/XcodesOrg/XcodesApp/assets/48277075/1f386417-ceb1-4f5e-99ff-3f5472aebed0)

**Version**
 - OS: 13.5.2
 - Xcodes:1.10.0

**Comment by martinmose** [comment]
I encountered a 412 error when I attempted to log in with a user not associated with an Apple Developer account. It was crucial to accept the developer program license agreement before I could log in successfully.

**Comment by DeepSeaLemon** [comment]
> 当我尝试使用未与 Apple 开发者帐户关联的用户登录时，遇到 412 错误。在成功登录之前，接受开发者计划许可协议至关重要。

Thank you for your answer, I can use it normally
