### ISSUE TITLE
Indicate visionOS SDK bundled with Xcode

### ISSUE THREAD

**Issue by jaanus** [XcodesOrg/XcodesApp#432]
Observed: there is no indication of visionOS SDK bundled with Xcode.

Expected: for the Xcode versions that have visionOS, this UI should indicate it.

Note that currently the mainline Xcode 15 doesn’t have visionOS yet, only Xcode 15 betas have it.

<img width="273" alt="Screenshot 2023-10-06 at 10 28 39" src="https://github.com/XcodesOrg/XcodesApp/assets/184253/242fabb4-cd03-4ef1-9110-1666ef2d46af">

**Comment by calimarkus** [comment]
It's being added in PR https://github.com/XcodesOrg/XcodesApp/pull/400, which is open since June..

**Comment by MattKiazyk** [comment]
2.0 (beta) is out now with all the VisionOS bits. Thanks!
