### ISSUE TITLE
MacOS Sonoma version 14 is incompatible with Xcode 15.0 (15A240d) switch 14.2 (14C18). Download the latest version for free from the App Store.

### ISSUE THREAD

**Issue by Mr-SunJun** [XcodesOrg/XcodesApp#434]
**Describe the bug**
After installing a different version of xcode, when I open it and run it, it says that I need to update to the latest version, which is not compatible with macOS Sonoma.

**To Reproduce**
Download the different versions of xcode and open them ，Switching between old and new versions and large versions, switching when not compatible with the system version

**Expected behavior**
My version is the MacOS Sonoma 14 version, and I want to use a lower version to adapt to other development tools to assist in development. Because the development tool displays the specified version, it cannot recognize this version. I am not sure if Xcodes version management can be achieved. Regardless of the Mac system version, I can switch to the XCode version and fully adapt to it, Or perhaps I misunderstood this tool and it can only switch xcode around Mac system version adaptation

**Screenshots**
![image](https://github.com/XcodesOrg/XcodesApp/assets/74604156/ed8751a4-cb10-4cb9-a2a1-c6260104d1d7)

**Version**
 - OS: macOS Sonoma 14
 - Xcodes: Xcode 15.0(15A240d) switch 14.2(14C18)

**Comment by chickdan** [comment]
This is a limitation of macOS rather than Xcodes, see this [Apple Developer forum](https://developer.apple.com/forums/thread/731005) discussion (note: there is a workaround in the discussion).
