### ISSUE TITLE
Unable to Sign In error 412

### ISSUE THREAD

**Issue by abush1** [XcodesOrg/XcodesApp#438]
**Describe the bug**
I am attempting to install Xcodes on my new MacBook Pro ARM64 device. When I select version 15 and try to install I am informed it needs permissions so I have to sign in with my iCloud account. When I try to sign in as my iCloud account I get either a 412 error OR told I have the wrong code when getting it through sms

**To Reproduce**
select sign in
enter appleID
enter password
get prompted with code (write it down) 
enter code
get error 412 unexpected status code. If I continue to have problems submit a bug report. 
click dismiss
click send sms
enter pass code received on phone
informed code does not match

**Expected behavior**
Enter appleId
enter password
enter passcode
Get signed in
select version of Xcode to install
version installed

**Screenshots**

**Version**
 - OS: 14
 - Xcodes:1.10.0

**Comment by liuz116110** [comment]
<img width="260" alt="image" src="https://github.com/XcodesOrg/XcodesApp/assets/51959845/03692aa1-59eb-4ac8-be08-e646aabee973">
一样的问题

**Comment by liuz116110** [comment]
https://github.com/XcodesOrg/XcodesApp/issues/417  这里有解决办法
