### ISSUE TITLE
Download and install Xcode Simulator runtimes

### ISSUE THREAD

**Issue by rennarda** [XcodesOrg/XcodesApp#457]
Xcode is no longer bundled with the iOS simulator runtime, which must be installed separately using Xcode itself. These downloads are substantial, and often very slow...

It appears that the full manifest of downloadable assets is available [here ](https://devimages-cdn.apple.com/downloads/xcode/simulators/index2.dvtdownloadableindex). It should therefore be possible to offer these as additional downloads in Xcodes, and utilise the fast download architecture.  

Downloaded runtimes can be added to Xcode using the command line `xcrun simctl runtime add <path>` - so it should also be possible for Xcodes to install these directly.

**Comment by chickdan** [comment]
This feature was implemented in #448 and will be available in the next release (hopefully soon).

**Comment by MattKiazyk** [comment]
@rennarda 2.0 Beta is ready to test do download runtimes/platforms. Thanks!
