### ISSUE TITLE
Received an unexpected status code: 412. If you continue to have problems, please submit a bug report in the Help menu.

### ISSUE THREAD

**Issue by jonlpqo** [XcodesOrg/XcodesApp#458]
**Describe the bug**
apple id sign in error

**Version**
 - OS: 14.1.1 (23B81)
 - Xcodes: 1.10.0(18)

**Comment by anthony-novikov** [comment]
If you use a newly created apple id, you need to login to https://developer.apple.com/account first and accept terms and conditions there. Then you'll be able to sign in to XCodes. At least this is what helped me to sign in.

**Comment by MattKiazyk** [comment]
412 on 2.0 (Beta) should show you the appropriate message now when getting the T&C error. Thanks!
