### ISSUE TITLE
New Release Soon?

### ISSUE THREAD

**Issue by chickdan** [XcodesOrg/XcodesApp#466]
The last release was in February and a lot of work has gone into the app since then with many fixes and QoL changes. If you ask me, it's due for an update. Do you have plans for creating a new release soon?

**Comment by MattKiazyk** [comment]
Hi @chickdan 

I hope to get a release out soon. I'm giving myself to the end of January to clean things up for a 2.0 release.

**Comment by chickdan** [comment]
Sounds good, thank you!

**Comment by MattKiazyk** [comment]
2.0 Beta is out now.. please test!
