### ISSUE TITLE
install helper failed

### ISSUE THREAD

**Issue by yigegongjiang** [XcodesOrg/XcodesApp#478]
**Describe the bug**
cannot install helper

**To Reproduce**
1. setting - advanced - install helper - input password - fail
2. select xcode - make active - install helper pop window - input password - fail

**Expected behavior**
now，cannot make xcode active.

**Screenshots**
<img width="260" alt="image" src="https://github.com/XcodesOrg/XcodesApp/assets/6027516/b4b01e0f-8226-4ae7-ac4f-d78acea07b56">
<img width="260" alt="image" src="https://github.com/XcodesOrg/XcodesApp/assets/6027516/6bd57f7e-7476-4a15-8c64-c3ed3217f2d6">

**Version** 
 - OS:  Mac with intel chip
 - Xcodes: 2.0.0(20)

**Comment by MattKiazyk** [comment]
@yigegongjiang can you try https://github.com/XcodesOrg/XcodesApp/pull/480 and let me know if that fixes for you?

**Comment by yigegongjiang** [comment]
@MattKiazyk hi，I am using the latest code from the `matt/privilegedHelperUpdate` branch and compiling the project locally. But the problem is not solved.

<img width="1400" alt="image" src="https://github.com/XcodesOrg/XcodesApp/assets/6027516/8a108b08-8ea7-43a9-8f6d-1ddadc10601e">
<img width="972" alt="image" src="https://github.com/XcodesOrg/XcodesApp/assets/6027516/deadd9b7-c05c-4668-bddb-6106910ca685">
<img width="1792" alt="image" src="https://github.com/XcodesOrg/XcodesApp/assets/6027516/f097df96-ad7c-4b28-8274-84453e22fc13">

**Comment by MattKiazyk** [comment]
@yigegongjiang thanks for the feedback. I'm hoping it's just because you don't have access to Apple Team and therefore it's giving you errors. We'll try on a newer beta soon.
