### ISSUE TITLE
Getting this error since the lates tupdate - probably as the new app is built with a sandbox

### ISSUE THREAD

**Issue by debanjanbasu** [XcodesOrg/XcodesApp#485]
**Describe the bug**
Unable to install Privileged Helped

**To Reproduce**
![image](https://github.com/XcodesOrg/XcodesApp/assets/10209115/c95d175f-f5b5-4057-9415-d9b99665a4fd)
![image](https://github.com/XcodesOrg/XcodesApp/assets/10209115/a98aad71-e276-4db8-a92c-ff5afded59e8)
![image](https://github.com/XcodesOrg/XcodesApp/assets/10209115/339bac5a-e88b-4b34-92f2-b6d741e4dfdd)

**Expected behavior**
Should install the helper

**Screenshots**

**Version**
 - OS: Sonoma 14.3
 - Xcodes: 15.2

**Comment by F1248** [comment]
Exactly the same error for me:

- MacBook Air M1
- macOS 14.3
- Xcodes 2.0.0 (20)

**Comment by MattKiazyk** [comment]
@debanjanbasu @F1248 Can you try this one? Just to double check things are working on none my end? 

Thanks
[Xcodes.zip](https://github.com/XcodesOrg/XcodesApp/files/14033383/Xcodes.zip)

**Comment by maxoriggi** [comment]
Hello,
I have had the same issue here and I can confirm that the attached version works correctly.
Let me know if you need further tests.

**Comment by PatrikTheDev** [comment]
This new build works correctly, thanks!

**Comment by tinder-cfuller** [comment]
FWIW, I also experienced the issue and the build attached above works as expected 👍

**Comment by MattKiazyk** [comment]
Thanks. 2.0.2 is out and should have this fix in.
