### ISSUE TITLE
International language not in effect

### ISSUE THREAD

**Issue by mdddj** [XcodesOrg/XcodesApp#492]
<img width="355" alt="image" src="https://github.com/XcodesOrg/XcodesApp/assets/29020213/4b69ece4-f3b4-4f09-a566-7204e7746bf9">
<img width="266" alt="image" src="https://github.com/XcodesOrg/XcodesApp/assets/29020213/ed62730f-e7b9-4fa7-8147-b1dcb5fabf2e">

**Comment by MattKiazyk** [comment]
Thanks @mdddj - it was my assumption that if a language didn't have a key it would use the default english language, but now using the .xcstrings that was a wrong assumption.

I'll have to go through and put in default english values in I guess, unless there's a way to default to english if a language value isn't there?

**Comment by MattKiazyk** [comment]
Fixed a bunch of these to set the default english in #532
