### ISSUE TITLE
can't install iOS17.2 for xcode15.2

### ISSUE THREAD

**Issue by talka123456** [XcodesOrg/XcodesApp#493]
**Describe the bug**
can't install iOS17.2 for xcode15.2, failture at install step

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="309" alt="iShot_2024-01-30_17 42 24" src="https://github.com/XcodesOrg/XcodesApp/assets/20468636/97618d34-f88e-4a55-b38f-01765aac1108">

**Version**
 - OS: 
 - Xcodes:

**Comment by MattKiazyk** [comment]
hi @talka123456 

At the bottom (of the awkward error message) it states: `Cannot copy the image because the disk is almost full` - which would indicate your harddrive is full that it can't finish what it needs to.

let me know if that helps?
