### ISSUE TITLE
Is "mini mode" (or "classic mode") needed ?

### ISSUE THREAD

**Issue by hackenbacker** [XcodesOrg/XcodesApp#494]
Version 2.0 is a very nice evolution.👏
However, I feel it takes up a lot of desktop space.
I think a "mini mode" (or classic mode) with minimal display is needed.
How do you like it?

### AS IS
<img width="800" src="https://github.com/XcodesOrg/XcodesApp/assets/22875818/117b0f0f-7b32-4ecb-b3b1-fda969730e13">

### TO BE

**Mini mode**
<img width="375" src="https://github.com/XcodesOrg/XcodesApp/assets/22875818/2c83e64d-982a-4b05-8ee9-2a368eacf2db">

**Expand**
<img width="800" src="https://github.com/XcodesOrg/XcodesApp/assets/22875818/91cfb736-9954-481f-a4aa-46775c405810">

**Comment by MattKiazyk** [comment]
Hi @hackenbacker thanks for the feedback.

I chose to go with the split navigation on v2 as I needed more room for the Platform download section. Prior version of Xcode you just needed to download one `xip` file. Now, you need to download xcode AND runtimes, so wanted to have 2 full sections always open.

If you're needing to simply switch between versions, perhaps a menu item would better suite that?
