### ISSUE TITLE
Download old simulator on last Xcode

### ISSUE THREAD

**Issue by pavel-trafimuk** [XcodesOrg/XcodesApp#500]
**Tell us how we can improve Xcodes**
First of all, thanks for you great job and app.
Starting using I found what I missed - current list of Xcode versions shows only latest simulators for this Xcode version:
e.g. Xcode 15.2 presents simulator for iOS 17.3

But during developing I need also older devices support - e.g. iOS Simulator 15.4, which I should download via Xcode (so slowly)

It will be great to see this list in your app also

**Is your feature request related to a problem? Please describe.**

**What would you like to see? How would you like it to work?**

**Comment by rtharston** [comment]
The older simulators are available under the older versions of Xcode. e.g. iOS Simulator 15.4 is available under Xcode 13.3 or 13.3.1.

<img width="1030" alt="Screenshot 2024-02-28 at 1 38 00 PM" src="https://github.com/XcodesOrg/XcodesApp/assets/12513211/96663d64-8dec-43f2-8759-84716745a3ac">

I think it would be handy to have all the available platforms available in the Platforms window, but at least for now you can at least get at them all, you just have to do a bit of hunting. 😁

**Comment by MattKiazyk** [comment]
Thanks @pavel-trafimuk - the missing platform on 15.3 is fixed in https://github.com/XcodesOrg/XcodesApp/pull/523.

Also working on having the platforms view just be more then just the installed platforms.
