### ISSUE TITLE
Xcode 15.3 Beta 2 (15E5188j) Doesn't Show visionOS in SDK list

### ISSUE THREAD

**Issue by mikaelacaron** [XcodesOrg/XcodesApp#501]
**Describe the bug**
In the list of SDKs in the details when clicking on 15.3 Beta 2, it doesn't show visionOS

**To Reproduce**
* Click on 15.3 Beta 2 (15E5188j)
* See detail view and under SDKs, visionOS 1.1 isn't listed

**Expected behavior**
* See visionOS versions as well

**Screenshots**
![Screenshot 2024-02-09 at 12 18 03 AM](https://github.com/XcodesOrg/XcodesApp/assets/22946902/7c0d423b-5c96-4e23-9e25-a6041be9c026)

**Version**
 - OS: macOS 14.2.1
 - Xcodes: 1.4.0(12)

**Comment by MattKiazyk** [comment]
Hey @mikaelacaron if you update to v2.0 you'll be able to download runtimes!

**Comment by mikaelacaron** [comment]
Thanks! I just tried to click "Check for updates" from the menu bar, but I'm getting an error, do I need to just completely delete this one and download v2.0?

**Comment by MattKiazyk** [comment]
You were on a really old version so guessing something changed between the subsequent releases that is causing the update not to work. Re downloading is your best bet then. Sorry about that. Make sure you turn on automatically check for updates to make sure you're up to date.

**Comment by mikaelacaron** [comment]
Ohhhh gotcha thanks!
