### ISSUE TITLE
Missing info in info pane

### ISSUE THREAD

**Issue by rtharston** [XcodesOrg/XcodesApp#512]
**Describe the bug**
All the right column info (release date, SDKs, etc) is missing when I select an installed version of Xcode, but they do show up for versions that aren't installed.

Also, no information is displayed in the PlatformsView in InfoPane when I select a version of Xcode (installed or not), but they do show up in the Platforms window.
UPDATE: They _did_ show up in the Platforms window the first time I opened it, but now it is blank too. 🤔

**To Reproduce**
Select an installed version of Xcode in the list.
Maybe the issue is related to using a non-default install location for Xcode?
<img width="493" alt="Screenshot 2024-02-28 at 9 27 34 AM" src="https://github.com/XcodesOrg/XcodesApp/assets/12513211/71705488-1f33-4878-80c6-e3ef3e3c9fb9">

**Expected behavior**
All the information that shows for uninstalled versions should show for installed versions too.
And the Platforms list should be populated (maybe a separate issue?)

**Screenshots**
<img width="1038" alt="Screenshot 2024-02-28 at 9 21 09 AM" src="https://github.com/XcodesOrg/XcodesApp/assets/12513211/803d48a0-3558-4da8-acc7-692b99043ea8">
<img width="1038" alt="Screenshot 2024-02-28 at 9 21 12 AM" src="https://github.com/XcodesOrg/XcodesApp/assets/12513211/f63c61c6-a8f6-4f34-bb3a-b69d7dac2a32">

**Version**
 - OS: 14.3.1
 - Xcodes: 2.0.2

**Comment by rtharston** [comment]
I tried diagnosing and fixing the issue myself so I could make a PR instead of an Issue, but when I try to run Xcodes locally the build crashes on launch in some assembly code, and I can't get the previews to work either (probably for the same reason), and unfortunately I don't have time right now to diagnose that _and_ the info issue. 😕

**Comment by MattKiazyk** [comment]
@rtharston  Can you change your datasource to be `Xcode Releases` instead of Apple - that should fix your issue. 

It still is a bug, where the platforms should still show.

**Comment by rtharston** [comment]
It is already set to `Xcode Releases`. Note that all the info is present when I select uninstalled versions of Xcode. It is only missing for installed versions.

**Comment by MattKiazyk** [comment]
hmmm, ok can you try deleting the `available-xcodes.json` and `downloadable-runtimes.json` from the local cache path? 

Then hit refresh. If the platforms don't show up then, it means it's having trouble connecting to https://devimages-cdn.apple.com/downloads/xcode/simulators/index2.dvtdownloadableindex to download them.

**Comment by rtharston** [comment]
That was it!

When I updated from version 1.10 all my settings were reset and a new set of json files were created in ~/Library, so I changed the settings to point at my old json files. That also explains why I remember seeing the Platforms info show up the first time I opened the application, it was still using the new files!

So I take it the format changed between 1.x and 2.0?

**Comment by MattKiazyk** [comment]
The format of `available-xcodes` i believe wouldn't have changed. `downloadable-runtimes` is new in 2.0 so that would have been added. 

Glad things worked out for you!

**Comment by rtharston** [comment]
By the way, I'm loving the new info pane! Adding the platforms install buttons for each Xcode version is a great touch.

**Comment by rtharston** [comment]
Then maybe I just needed to hit 'refresh' to recreate `downloadable-runtimes`. I hit the same issue on my desktop computer this morning so I can try just hitting refresh on that computer when I get home. I imagine that will do it.

**Comment by MattKiazyk** [comment]
It should do that on it's own when you first open the app, but if you haven't closed the app in a while, you'll need to manually do ti.

**Comment by rtharston** [comment]
When it first opened it was still pointing at Library instead of my custom location.

So I guess there are two questions here. Why did 2.0 reset my custom location? And should changing the location cause a refresh?

**Comment by rtharston** [comment]
Yep, hitting refresh fixed everything on my desktop. I guess I didn't think to try that since the Xcodes list was populated.
