### ISSUE TITLE
helper not installed

### ISSUE THREAD

**Issue by Grant-Perry** [XcodesOrg/XcodesApp#518]
When i attempt to install anything xcodes tryes to load some helper - and then i get the "Unable to select Xcode" with (CFErrorDomainLaunchd.4) error. 

I've tried to figure out what it needs and how to install it but alas, no.

It's when i try to remove/install/Make Active on any build.

Argghhh...

**Comment by MattKiazyk** [comment]
Hi @Grant-Perry 

Please make sure you're on the latest version (2.0.2). Some fixes were included dealing with the privileged helper. 

You can try installing it manually via `Settings > Advanced`. 

Hopefully that helps you.

**Comment by Grant-Perry** [comment]
STOP EVERYTHING… 2.0.2 fixed it; thanks.

And for certain, thanks for the app!

Gp.

Sent from my iPhone

From: Grant Perry ***@***.***>
Date: Wednesday, March 6, 2024 at 1:47 PM
To: XcodesOrg/XcodesApp ***@***.***>, XcodesOrg/XcodesApp ***@***.***>
Cc: Grant Perry ***@***.***>, Mention ***@***.***>
Subject: Re: [XcodesOrg/XcodesApp] helper not installed (Issue #518)
Matt,

First off – that was effing amazing. I literally just hit enter on the form and you’re already respoding; clutch!

Second – I use Xcodes EVERY SINGLE DAY! Thank you.

So, ya, I tried installing it via Advanced and I’m getting this:

[A screenshot of a computer  Description automatically generated]

Command line tools are installed so I’m not certain.

Also, on the Platforms screen, there is a trash can icon to delete, but it does nothing!

Thanks so much.

Gp.



From: Matt Kiazyk ***@***.***>
Date: Wednesday, March 6, 2024 at 1:36 PM
To: XcodesOrg/XcodesApp ***@***.***>
Cc: Grant Perry ***@***.***>, Mention ***@***.***>
Subject: Re: [XcodesOrg/XcodesApp] helper not installed (Issue #518)

Hi @Grant-Perry<https://github.com/Grant-Perry>

Please make sure you're on the latest version (2.0.2). Some fixes were included dealing with the privileged helper.

You can try installing it manually via Settings > Advanced.

Hopefully that helps you.
