### ISSUE TITLE
Sidebar Behavior

### ISSUE THREAD

**Issue by andreyoshev** [XcodesOrg/XcodesApp#525]
**Describe the bug**
Unable to expand the sidebar if you accidentally hid it.

**To Reproduce**
1. Grab sidebar border;
2. Pull it until it's gone.

**Expected behavior**
Have a button to expand it manually 
![CleanShot 2024-03-11 at 10 24 43@2x](https://github.com/XcodesOrg/XcodesApp/assets/17673010/b14f867e-e705-4f6b-b077-8cfadda01b57)

**Screenshots**
![CleanShot 2024-03-11 at 10 20 27@2x](https://github.com/XcodesOrg/XcodesApp/assets/17673010/c3976acc-a264-4562-b8ab-0b4a6d7f9a77)

**Version**
 - OS: Sonoma 14.3.1
 - Xcodes: 2.0.2

**Comment by MattKiazyk** [comment]
Thanks @andreyoshev this is fixed in https://github.com/XcodesOrg/XcodesApp/pull/499 and will be in the next release. Thanks!
