### ISSUE TITLE
Missing data/text with latest update

### ISSUE THREAD

**Issue by marlonjames71** [XcodesOrg/XcodesApp#534]
**Describe the bug**
Text is missing in the sidebar and the details view with the latest update (2.1.1 (25)) it looks like. Looks like the search bar is scrunched as well. 

**To Reproduce**
Steps to reproduce the behavior: Just open the app.

**Expected behavior**
I expected text and data to show in the app.

**Screenshots**
![CleanShot 2024-03-16 at 23 07 26@2x](https://github.com/XcodesOrg/XcodesApp/assets/48145861/9dae926b-ece3-4602-a6cc-f2c5ed4bdd19)

**Version**
 - OS: Sonoma 14.4
 - Xcodes: 2.1.1 (25)

**Comment by MattKiazyk** [comment]
Thanks - looks like it's a MacOS 14.4 issue. Was looking ok on 14.1/14.3 on my test computers. Will update and see what it is.

Work around is go back to 2.0.X version https://github.com/XcodesOrg/XcodesApp/releases/tag/v2.0.2b23

**Comment by marlonjames71** [comment]
#Yeah that could be for sure. And I'll make sure to download a previous version. Curious, is this an AppKit or SwiftUI app?

**Comment by marlonjames71** [comment]
Never mind. Just checked and looks like SwiftUI.

**Comment by MattKiazyk** [comment]
v2.1.2 is available to fix this issue
