### ISSUE TITLE
The layout is broken after upgrade to Version 2.1.1

### ISSUE THREAD

**Issue by ShayTSC** [XcodesOrg/XcodesApp#537]
**Describe the bug**
The layout of the list of the XCode versions are broken as shown below in the Screenshot section.

**To Reproduce**
Install XCodes from the Github release to my MacBook Pro, which installed macOS Sonoma 14.4 with Chinese Simplified lanaugage as System Language.

**Expected behavior**
A not broken layout, I suppose 🤣 
Bue seriously, the input search is so short, it must be broken, and there should be text of the XCode version number in each list item.
I think this is some special thing happend with SwiftUI and Chinese translation, but I can't be sure. I'll switch my System Language to English later just to test it out.

**Screenshots**
![CleanShot 2024-03-17 at 19 42 51@2x](https://github.com/XcodesOrg/XcodesApp/assets/10642396/22e8eee2-0973-4fb7-a7a4-3d77a63d1a8b)

**Version**
 - OS: macOS Sonoma 14.4
 - Xcodes: 2.1.1

**Comment by vvisionnn** [comment]
same here🙋🏼 same issue for the layout
