### ISSUE TITLE
Managed Preferences for Xcodes.app

### ISSUE THREAD

**Issue by abiligiri** [XcodesOrg/XcodesApp#565]
**Tell us how we can improve Xcodes**
Allow Xcodes.app to disallow changes to preferences that are configured at the system level using managed preferences

**Is your feature request related to a problem? Please describe.**
It is common for some enterprise environments to require some preferences like install location, Xcode feed source, beta/release to be set by the administrator. This is mostly to meet some compliance requirements. This can be partially achieved by setting these values using MDM tool, but the end user can still override from in-app.

**What would you like to see? How would you like it to work?**
If a preference value is set by MDM, in-app settings could be greyed out or disabled, disallowing user from updating the same.

**Comment by abiligiri** [comment]
https://github.com/XcodesOrg/XcodesApp/pull/569 is an attempt to restrict edits to preferences that are managed by MDM.

**Comment by abiligiri** [comment]
@MattKiazyk please provide feedback on this and associated pull request.

**Comment by abiligiri** [comment]
I have made a binary available here https://github.com/abiligiri/XcodesApp/releases/tag/2.1.2.103 with the changes

**Comment by MattKiazyk** [comment]
This is available starting in [v2.3.0 ](https://github.com/XcodesOrg/XcodesApp/releases/tag/v2.3.0b28) Thanks
