### ISSUE TITLE
Platforms downloading broken

### ISSUE THREAD

**Issue by MattKiazyk** [XcodesOrg/XcodesApp#571]
**Describe the bug**
Looks like Apple changed a few things on the platforms starting with Xcode 16 beta. 

`CryptexDiskImage` is a new type of image that isn't handled. 

```
<dict>
			<key>category</key>
			<string>simulator</string>
			<key>contentType</key>
			<string>cryptexDiskImage</string>
			<key>dictionaryVersion</key>
			<integer>2</integer>
			<key>downloadMethod</key>
			<string>mobileAsset</string>
			<key>fileSize</key>
			<integer>8455760175</integer>
			<key>identifier</key>
			<string>com.apple.dmg.iPhoneSimulatorSDK18_0_b1</string>
			<key>name</key>
			<string>iOS 18.0 beta Simulator Runtime</string>
			<key>platform</key>
			<string>com.apple.platform.iphoneos</string>
			<key>simulatorVersion</key>
			<dict>
				<key>buildUpdate</key>
				<string>22A5282m</string>
				<key>version</key>
				<string>18.0</string>
			</dict>
			<key>version</key>
			<string>18.0.0.1</string>
		</dict>
		```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**
 - OS: 
 - Xcodes:

**Comment by timsutton** [comment]
It looks like Apple now uses the same (private) MobileAsset framework, as a client for their Pallas service that they use for other OTA updates, to download these too now. They look a lot closer to device restore images now even though ultimately they're still a .runtime mounted at a path.
