### ISSUE TITLE
Support iOS 18 Beta Platforms

### ISSUE THREAD

**Issue by doganaltinbas** [XcodesOrg/XcodesApp#575]
That would be nice if we could add iOS 18 Beta simulators along with Xcode 16 Beta.

<img width="945" alt="Screenshot 2024-06-11 at 13 27 03" src="https://github.com/XcodesOrg/XcodesApp/assets/5463479/ac53bfa1-5e7e-4d89-8740-87922e50adb0">

**Comment by crystall1nedev** [comment]
The issue here isn't actually the fault of Xcodes. Apple switched to using their OTA server (the one that hands out iOS/macOS/etc OTA updates, among others, also known as "Pallas") for simulator runtimes.

**Comment by Lancelotbronner** [comment]
Well, is it possible to hit that server to get metadata?
