### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Euporie** [XcodesOrg/XcodesApp#579]
![image](https://github.com/XcodesOrg/XcodesApp/assets/5467373/82662b40-cca9-43eb-a7c6-c0df2a054634)
it should be “download”😂

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
Hi @Euporie , in which file please ?

**Comment by KaitoMuraoka** [comment]
I think this is a typo by [XcodesOrg](https://github.com/XcodesOrg), not by XcodesApp.

**Comment by Euporie** [comment]
> Hi @Euporie , in which file please ?

here it is: https://github.com/XcodesOrg

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
sorry but i still don't get it, what is the file i should modify ?

**Comment by MattKiazyk** [comment]
Thanks! Updated
