### ISSUE TITLE
Nothing showing up, cannot download more Xcodes

### ISSUE THREAD

**Issue by bartekpacia** [XcodesOrg/XcodesApp#607]
<img width="1364" alt="Screenshot 2024-08-30 at 15 55 11" src="https://github.com/user-attachments/assets/03b9e36d-6191-460c-b2f5-a00323e96575">

How do I install more versions?

**Comment by MattKiazyk** [comment]
Click the arrows on the far right tool bar or increase the size of your left nav 

macOS likes to move tool bar buttons when it doesn't have enough room to show them

**Comment by bartekpacia** [comment]
dang, you're right! so weird!

https://github.com/user-attachments/assets/718d1088-7b1b-4710-89fb-1b6cb436c746

thanks a ton!

**Comment by MattKiazyk** [comment]
Xcodes does not support downloading Xcode 16+ runtimes as Apple has changed how they are downloaded and it's not a simple fix and not sure it's even possible. 

Your best to use Xcode when downloading the runtimes for 16+

**Comment by bartekpacia** [comment]
Gotcha, thanks!
