### ISSUE TITLE
Error when attempting to install iOS 18 runtime

### ISSUE THREAD

**Issue by iosdevben** [XcodesOrg/XcodesApp#627]
**Describe the bug**

I tried to install the iOS 18 runtime but got this error:

![image](https://github.com/user-attachments/assets/772eb96d-7078-41e0-9741-6428e3e43ffd)

**Version**
 - OS: 15.0.1
 - Xcodes: 2.2.0 (27)

**Comment by MattKiazyk** [comment]
This will be fixed in the next release via https://github.com/XcodesOrg/XcodesApp/pull/622

Apple changed how they provide the runtimes in Xcode 16 and only starting in 16.1 Beta 3 do they give the option to download individual versions.

**Comment by MattKiazyk** [comment]
Latest version 2.3.0 has been released. iOS 18+ runtimes require Xcode 16.1 beta 3+ in order to download
