### ISSUE TITLE
I can't sign in with my Apple ID

### ISSUE THREAD

**Issue by alpennec** [XcodesOrg/XcodesApp#630]
**Describe the bug**
I try to sign in with my email address and password.

**To Reproduce**
Steps to reproduce the behavior: try to sign in within the app (Settings)

**Expected behavior**
I should receive a 2FA request on an associated device

**Screenshots**

**Version**
 - OS: macOS
 - Xcodes: 2.3.0 (28)

![CleanShot 2024-10-18 at 23 07 14@2x](https://github.com/user-attachments/assets/a4b44346-f5d2-4179-aa8c-a822e06d54a0)

**Comment by paytontech** [comment]
same issue here
<img width="431" alt="Screenshot 2024-10-18 at 5 53 04 PM" src="https://github.com/user-attachments/assets/301fd549-774a-4e86-b308-2e0d49415ada">

**Comment by flynncupitt** [comment]
Also having the same issue with the same error

**Comment by utamori** [comment]
me too

**Comment by MattKiazyk** [comment]
Looks like the sign in URL's are getting 503's now...
```
https://idmsa.apple.com/appleauth/auth/signin } { Status Code: 503, Headers {
    Connection =     (
        "keep-alive"
    );
    "Content-Length" =     (
        190
    );
    "Content-Type" =     (
        "text/html"
    );
    Date =     (
        "Sat, 19 Oct 2024 02:10:35 GMT"
    );
    Server =     (
        Apple
    );
} }
```

**Comment by alpennec** [comment]
This is something I observed too while using another library using the same URL to sign in to an Apple account. Is it possible Apple changed something to prevent these kind of logins? Is there a new way to do that now?

**Comment by vincentzchao** [comment]
same issue
<img width="400" alt="image" src="https://github.com/user-attachments/assets/19328a24-44f2-4900-98c3-6e335d6c4496">

**Comment by dfed** [comment]
Welp. Same.

**Comment by SoftMochii** [comment]
Same issue here

**Comment by jingfelix** [comment]
Same. Thought I was blocked by Apple 😅

**Comment by thierryH91200** [comment]
Same issue

**Comment by stnor** [comment]
Yup same here

**Comment by vv-m** [comment]
I have tried version 2.1 and 2.2 - the issue is same.

**Comment by alpennec** [comment]
At this point, I don't think authentication within the app will work again until the new authentication method used by Apple is cracked. Some progress in the fastlane issue [here](https://github.com/fastlane/fastlane/issues/26368).

**Comment by nolann-dev** [comment]
Same issue

**Comment by dmisav** [comment]
same here
![image](https://github.com/user-attachments/assets/254b1275-5a87-4df5-ac8b-4828132fcc76)

Sonoma 14.1.1
Xcodes: 2.3.0

**Comment by MattKiazyk** [comment]
Hey everyone. Please be patient as I work through the changes to log in. 

It is effecting everyone regardless of version or OS so no need for any extra comments. 

Workaround is to log into developer.apple.com and download it manually. Runtimes do not require logins so those will still work.

**Comment by hzlzh** [comment]
same here

**Comment by Ricardo1980** [comment]
Same issue

**Comment by mgreenbin** [comment]
I don't kmow if this helps, but it worked on Oct 18th on a Macbook Pro running Sequoia 15.01 but not on Oct 19th on a Macbook Pro running Senoma 14.5.

**Comment by stnor** [comment]
> I don't kmow if this helps, but it worked on Oct 18th on a Macbook Pro running Sequoia 15.01 but not on Oct 19th on a Macbook Pro running Sonoma 14.5.

It's apparently related to a change in Apple's authentication apis.

**Comment by shainmack** [comment]
Same issue, following for resolution

**Comment by Stp155906** [comment]
<img width="1041" alt="Screenshot 2024-10-20 at 1 32 33 PM" src="https://github.com/user-attachments/assets/107881f8-98d1-4ee1-b821-de87096f949b">
SAME ISSUE.

**Comment by farooqaziz20** [comment]
Same issue, Please update when this can be resolved.

**Comment by pastorin** [comment]
same issue - following

**Comment by schwa** [comment]
Yup. Same - tracking issue.

**Comment by TofPlay** [comment]
Same issue

**Comment by dennis777** [comment]
same issue - following

**Comment by KSemenenko** [comment]
I have the same issue too

**Comment by m1entus** [comment]
+1

**Comment by JoanRojasMejia** [comment]
Same issue

**Comment by sabiland** [comment]
Sam issue.

**Comment by woodyhayday** [comment]
+1

**Comment by EmirogluFurkan** [comment]
+1

**Comment by prince-housing** [comment]
+1

**Comment by itslazyvar** [comment]
It looks like the fix that fastlane implemented, as [mentioned](https://github.com/XcodesOrg/XcodesApp/issues/630#issuecomment-2425421742) by @davedelong, involved rolling @snatchev's[ fork of sirp](https://github.com/snatchev/sirp) (and the work he did on it) into @fastlane. 

It might not be as straightforward for us because it's in Ruby, but between the work and documentation on the fork and the implementation details by fastlane, we should have enough information to create a solution in Swift.

**Comment by MattKiazyk** [comment]
I'm working on it in the evenings when family and work stuff is done. My first pass last night didn't pan out, and is highly to do with me not fully understanding crypto enough to be productive in the space. If there are dev's that are more knowledgable in the crypto world and can translate the library, I'm all for the help.

**Comment by pyrtsa** [comment]
Just googling around, did you check out https://github.com/adam-fowler/swift-srp?

**Comment by KSemenenko** [comment]
Any change there is some solution like https://developer.apple.com/documentation/authenticationservices/implementing-user-authentication-with-sign-in-with-apple. Will works?

**Comment by dqhieu** [comment]
I have the same issue

**Comment by MattKiazyk** [comment]
Ok I need some help 🙏 

I've tried for several nights trying to get things to work, and haven't had success. My Cryptography course 25 years ago isn't paying off. 

I've pushed a branch - https://github.com/XcodesOrg/XcodesApp/tree/matt/SRPLogin 
- There's a `srpLogin` call that starts everything and has the outline for the calls to Apple - `/init` `/complete`. 
- There is a local swift package called swift-srp which is a fork of https://github.com/adam-fowler/swift-srp. 
- I've added some changes to which I thought was needed.
- I'm trying to base the calculations on fastlane's implementation (https://github.com/fastlane/fastlane/pull/26415/files) 

I think I'm close - so i'm now asking for help if anybody has more knowledge that could get this over the finish line.

**Comment by Lakr233** [comment]
Gonna take a look on this.

**Comment by Lakr233** [comment]
Task complete. See https://github.com/Lakr233/AppleWebLogin for my code.

In my understanding, directory service id, aka prsId, is the only stuff we need to download packages from App Store. And, by using my package, user is able to sign in via touch id.
 
<img width="608" alt="SCR-20241023-qdoh-2" src="https://github.com/user-attachments/assets/14df7d98-c072-4839-ad10-ebc380328835">

**Comment by Lakr233** [comment]
I've found this very useful. Might be better if you are looking for something more robust.

https://github.com/blacktop/ipsw/blob/ac1720a71c1526ec4dbe7e2aee718ffee2d96a65/internal/download/dev_portal.go#L754

**Comment by MattKiazyk** [comment]
> Task complete. See https://github.com/Lakr233/AppleWebLogin for my code.
> 
> In my understanding, directory service id, aka prsId, is the only stuff we need to download packages from App Store. And, by using my package, user is able to sign in via touch id.
> 
> <img alt="SCR-20241023-qdoh-2" width="608" src="https://private-user-images.githubusercontent.com/25259084/379226324-14df7d98-c072-4839-ad10-ebc380328835.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTI5MTYsIm5iZiI6MTcyOTY5MjYxNiwicGF0aCI6Ii8yNTI1OTA4NC8zNzkyMjYzMjQtMTRkZjdkOTgtYzA3Mi00ODM5LWFkMTAtZWJjMzgwMzI4ODM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE0MTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YjBlMjJkNGU0ZWU5NjU1OTgyYjAwNmE5MzYwNTFmOGQxY2I2YzYyNGQwMzlkZWM4MTU3M2E4ODhkNjg3ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9lNEnBSBtCj3GNW3_k2DVFI7mMtf3j_m6az-evvWeyE">

Interesting approach - let me play with this! Thanks

It won't however work for the CLI - so the original problem still exists but if the UI doesn't need to ask for password I'm all for it.

**Comment by IgorMuzyka** [comment]
same

**Comment by MattKiazyk** [comment]
> Task complete. See https://github.com/Lakr233/AppleWebLogin for my code.
> 
> In my understanding, directory service id, aka prsId, is the only stuff we need to download packages from App Store. And, by using my package, user is able to sign in via touch id.
> 
> <img alt="SCR-20241023-qdoh-2" width="608" src="https://private-user-images.githubusercontent.com/25259084/379226324-14df7d98-c072-4839-ad10-ebc380328835.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3Mzc2NDEsIm5iZiI6MTcyOTczNzM0MSwicGF0aCI6Ii8yNTI1OTA4NC8zNzkyMjYzMjQtMTRkZjdkOTgtYzA3Mi00ODM5LWFkMTAtZWJjMzgwMzI4ODM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDAyMzU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZjUxNDI0MTBkYjkzZGZiNmQ3ZjQ3MjNmNTQxMzJlNDYxNGVlNGI2NWMyM2VjNGE4MGNhNThkYjM4YTc4NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IbsI5PgwI7A8kI8q0twp7YddNu05pYX4eq1ENTtL7bU">

@Lakr233 
So in my tests, while this allows the user to log in, and you can get a user object, the `acinfo` cookie is not enough to give authorization to the download URL - ie: `https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_16.2_beta_1/Xcode_16.2_beta_1.xip`.

**Comment by Lakr233** [comment]
The request come in two path, first request is as the url provided above.

```
curl https://developer.apple.com/services-account/download\?path=/Developer_Tools/Xcode_16.2_beta_1/Xcode_16.2_beta_1.xip -k -v \
    -H "cookie: myacinfo=xxx"
```

This will return a new cookie called `download auth` inside the header:
```
< set-cookie: ADCDownloadAuth=xxxxxxxx;Version=1;Comment=;Domain=apple.com;Path=/;Max-Age=108000;Secure;HttpOnly;Expires=Thu, 24 Oct 2024 03:12:25 GMT
```

With this header, you make another request corresponding to 302 status：
```
curl 'https://download.developer.apple.com/Developer_Tools/Xcode_16.2_beta_1/Xcode_16.2_beta_1.xip' -k -v \
    -H 'cookie: ADCDownloadAuth=xxxxxxx'
```

It will send you Xcode.
```
< HTTP/2 200 
< accept-ranges: bytes
< content-type: application/octet-stream
< server: AmazonS3
< content-length: 2865851655
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
```

If you are using URLSession to access first request, it will follow the 302 redirection but your cookie is discarded iirc.

If the code above does not work anyway, I suspect the code from `ipsw` cli is the solution we gonna copy.

**Comment by Lakr233** [comment]
> Interesting approach - let me play with this! Thanks

This will work within your binary command line Xcodes. As long as you don’t use SwiftUI and create things like NSWindow manually, you should be fine. Additionally, recent attackers have demonstrated that they can abuse the headless WebKit, which is invisible to users, to trigger the system-wide login dialog from a command line tool.

<img width="912" alt="image" src="https://github.com/user-attachments/assets/b9b199e5-65aa-4385-aed4-9059e0bd7e83">

Therefore/Additionally, I recommend copying my code into your repository to avoid any trust issues if you choose to go with my solution.

**Comment by Arlindo-g** [comment]
Fastlane also solved this the new auth process, if we can use what was done there as a reference:

- [PR](https://github.com/fastlane/fastlane/pull/26415)
    - mostly in this [file](https://github.com/fastlane/fastlane/pull/26415/files#diff-cbfb3283bb6f7c2275c3f5b92eee68ae77ab149bed0a5c66836bf5ad396f437e)

**Comment by MattKiazyk** [comment]
Update: I cleaned up a bunch of the code and have a simple SRP client, but something still doesn't work. If anybody else wants to look. https://github.com/XcodesOrg/XcodesApp/tree/matt/SRPLogin

**Comment by snatchev** [comment]
I don't know Swift, but I want to call out that Apple's algo does something non-standard here:
https://github.com/XcodesOrg/XcodesApp/compare/main...matt/SRPLogin#diff-e67960759f54af30fce32bb793cc6ed7a70a0b26304c10f1855e2ce87079e14bR119

Specifically, notice https://github.com/snatchev/sirp/blob/master/lib/sirp/sirp.rb#L115-L119

They are the 2 hashes are of hexstrings. So something like: `hash(hex(salt) + hash( hex(":" + password)))`.

**Comment by abiligiri** [comment]
I see that sometimes the encryptedPassword is nil https://github.com/XcodesOrg/XcodesApp/blob/matt/SRPLogin/Xcodes/AppleAPI/Sources/AppleAPI/Client.swift#L65

**Comment by aherrick** [comment]
Is there any work around to install greater versions without needing to login?

**Comment by Alien-hide** [comment]
> Is there any work around to install greater versions without needing to login?

use appstore

**Comment by smardine** [comment]
> Is there any work around to install greater versions without needing to login? 

You can go to https://developer.apple.com/download/all/?q=xcode  and download manually the version, once installed, the new version will appear as downloaded in xcodes app

**Comment by glunaTractian** [comment]
> > Is there any work around to install greater versions without needing to login?
> 
> You can go to https://developer.apple.com/download/all/?q=xcode and download manually the version, once installed, the new version will appear as downloaded in xcodes app

Tho if you have installed the latest MacOS Sequoia version, you'll probably stumble onto this 

![image](https://github.com/user-attachments/assets/1f9018bf-b659-49ed-b154-e9d73ea7a833)

Now I'm stuck on Xcode 16

**Comment by smardine** [comment]
> > > Is there any work around to install greater versions without needing to login?
> > 
> > You can go to https://developer.apple.com/download/all/?q=xcode and download manually the version, once installed, the new version will appear as downloaded in xcodes app
> 
> Tho if you have installed the latest MacOS Sequoia and Xcode version, you'll probably stumble onto this 
> 
> ![image](https://github.com/user-attachments/assets/1f9018bf-b659-49ed-b154-e9d73ea7a833)
> 
> Now I'm stuck on Xcode 16
> 

I'm being able to Switch to 15.4 xcodes version, but from xcodes.app

**Comment by fiznool** [comment]
Great to hear tht this is being actively worked on. Whilst I'm not able to contribute directly to this effort, I was wondering on a slightly different approach to the ones already mentioned.

There is a [swift-srp package](https://github.com/adam-fowler/swift-srp) that has already implemented SRP to the spec, and is packaged up in an easy-to-use format. As I understand it, the iCloud SRP implementation deviates slightly from this spec, but the library should get us most of the way there - to make the necessary modifications, we can then draw inspiration from some other implementations in different languages, for example [js-srp-gsa](https://github.com/foxt/js-srp-gsa). I feel like leaning on an already-existing implementation is a safer way to introduce the necessary crypographic changes, as it is best practice to reuse rather than reimplement in this specific domain of crypto.

It seems that the folks at fastlane have done something similar and wrapped this into a gem [fastlane-srp](https://github.com/fastlane/fastlane-sirp). Perhaps the same approach could be taken here, so a reusable library could be produced for both the Xcodes app and CLI?

**Comment by itsthejb** [comment]
> > > Is there any work around to install greater versions without needing to login?
> > 
> > 
> > You can go to https://developer.apple.com/download/all/?q=xcode and download manually the version, once installed, the new version will appear as downloaded in xcodes app
> 
> Tho if you have installed the latest MacOS Sequoia and Xcode version, you'll probably stumble onto this
> 
> ![image](https://private-user-images.githubusercontent.com/173080513/380434356-1f9018bf-b659-49ed-b154-e9d73ea7a833.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMjY2NDAsIm5iZiI6MTczMDAyNjM0MCwicGF0aCI6Ii8xNzMwODA1MTMvMzgwNDM0MzU2LTFmOTAxOGJmLWI2NTktNDllZC1iMTU0LWU5ZDczZWE3YTgzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxMDUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2I1YTVkZWNlM2M2NTQ0ODhjZjMxNDBlNGY3NjUyYjQ2MDExMjRhNzg5MTMzYjVlM2NkMzUwZWRlNjI4YjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YmOTCVLj-HvjT1afX4XonMnDbMtDNuUOKTnFJxX6V2o)
> 
> Now I'm stuck on Xcode 16

It's just a soft block. You can get it to run by setting the `CFBundleVersion` in 15.4's Info.plist to that of a supported version, e.g. Xcode 16. Very annoying aggressive upgrade push from Apple

This is unrelated to the issue with Xcode.app sign-in, though

**Comment by abiligiri** [comment]
> Update: I cleaned up a bunch of the code and have a simple SRP client, but something still doesn't work. If anybody else wants to look. https://github.com/XcodesOrg/XcodesApp/tree/matt/SRPLogin

Should the PBKDF be on SHA25 hash of the password ?
See 
`
 private async derivePassword(protocol: "s2k" | "s2k_fo", password: string, salt: Uint8Array, iterations: number) {
        let passHash = new Uint8Array(await util.hash(srp.h, stringToU8Array(password)));
`
here https://github.com/foxt/js-srp-gsa/blob/main/README.md

and 

https://github.com/fastlane/fastlane/blob/ec78d7d81a6a66e9e89fd29f6e0616d5ba09840a/spaceship/lib/spaceship/client.rb#L529

**Comment by rhysm94** [comment]
> > > Is there any work around to install greater versions without needing to login?
> > 
> > 
> > You can go to https://developer.apple.com/download/all/?q=xcode and download manually the version, once installed, the new version will appear as downloaded in xcodes app
> 
> Tho if you have installed the latest MacOS Sequoia and Xcode version, you'll probably stumble onto this
> 
> ![image](https://private-user-images.githubusercontent.com/173080513/380434356-1f9018bf-b659-49ed-b154-e9d73ea7a833.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjE2ODIsIm5iZiI6MTczMDEyMTM4MiwicGF0aCI6Ii8xNzMwODA1MTMvMzgwNDM0MzU2LTFmOTAxOGJmLWI2NTktNDllZC1iMTU0LWU5ZDczZWE3YTgzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQxMzE2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzQzODU0ODk2OGY4M2U2NTQ5NTUxYjYyOTIwNjE1YWRjZTcwNzJlMjE3YjE1ODMwODdlMTI0Y2YzMDkwYjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MXr2qndE1tFeICh19f3KjL0ofhBM6jfbXNqdaUHoqNY)
> 
> Now I'm stuck on Xcode 16

If you launch the actual executable in Xcode using Terminal, you _can_ (at least for the time being) run Xcode 15.4 on Sequoia.

**Comment by abiligiri** [comment]
I have two options to fix this

   1. https://github.com/XcodesOrg/XcodesApp/pull/638 that switches to a different package for SRP login with some modifications
   2. https://github.com/XcodesOrg/XcodesApp/pull/639 keeps the swift-srp

I would prefer to merge the first one as that also has some test with sample username/password

**Comment by MattKiazyk** [comment]
> I have two options to fix this
> 
> 1. [SRP Login works now #638](https://github.com/XcodesOrg/XcodesApp/pull/638) that switches to a different package for SRP login with some modifications
> 2. [Fix SRP Login #639](https://github.com/XcodesOrg/XcodesApp/pull/639) keeps the swift-srp
> 
> I would prefer to merge the first one as that also has some test with sample username/password

AMAZING! Thank you!

I did a quick test and I can log in. I prefer as well #638 too and like https://github.com/XcodesOrg/XcodesApp/pull/638#issuecomment-2442675215 indicated, I can fork those changes into the `XcodesOrg` repo to reuse it. 

The download still seems to be missing something, as it doesn't work, but this amazingly gets passed the SRP shenanigans. 

I am eternally grateful. I'll be back later on tonight to hopefully figure the rest out!

**Comment by abiligiri** [comment]
Sounds good. Happy to help.

**Comment by MattKiazyk** [comment]
Before releasing to the masses - here is a zip of Xcodes with the changes from https://github.com/XcodesOrg/XcodesApp/pull/638

If I could get some testers to give this a whirl and double check they can log in again and respond here that would be phenomenal 

Note: This is the same version number as current release. 

[Xcodes.zip](https://github.com/user-attachments/files/17551032/Xcodes.zip)

**Comment by davedelong** [comment]
@MattKiazyk that build worked for me

**Comment by RiceGTSTW** [comment]
@MattKiazyk it worked!

**Comment by jsorge** [comment]
@MattKiazyk Worked for me too!

**Comment by abiligiri** [comment]
Works!

**Comment by MattKiazyk** [comment]
Thank you to everybody for quick testing and especially to @abiligiri for getting this over the finish line! 

[v2.4.0](https://github.com/XcodesOrg/XcodesApp/releases/tag/v2.4.0b29) has been released which includes this fix.

**Comment by ygee07** [comment]
Hi, I tried logging in using `v2.4.0` but I'm getting this error:
"Invalid username and password combination."

Has anybody tested this macOS 15.2 ?

**Comment by Lakr233** [comment]
You probably need to logout and sign in inside settings.

**Comment by MattKiazyk** [comment]
From following along on [fastlane issue](https://github.com/fastlane/fastlane/pull/26415) for the SRP changes, a few people have had it not work. So there's a few things to try:

1. Make sure your email is all lowercase - some say that fixed it.
2. Actually log into developer.apple.com to make sure it works and Apple caches some things.

**Comment by ygee07** [comment]
I did try the following options with no avail:
1. Make sure email is all lowercase and no whitespace
2. Actually log into developer.apple.com in browser to make sure it works (works on browser).
3. Login through Xcodes Settings
4. Uninstall and Reinstall Xcodes
5. Use App-Specific Password

**Comment by smardine** [comment]
Installation of the new version on MacOS Sequoia 15.0.1 ok
authentication ok
Thanks sooo much

**Comment by KSemenenko** [comment]
it works perfect now! thanks a lot!

**Comment by MattKiazyk** [comment]
For those users still getting the invalid username/password on Xcodes 2.4.0 - could you please try updating to 2.4.1 and let me know if that fixes your issue?

**Comment by ygee07** [comment]
Changing the password worked for me, thank you
