### ISSUE TITLE
Can not login. 

### ISSUE THREAD

**Issue by mbonnette** [XcodesOrg/XcodesApp#633]
<img width="400" alt="Screenshot 2024-10-22 at 4 10 21 PM" src="https://github.com/user-attachments/assets/0b01cb2a-4072-4f3e-99de-ae4cc075debc">

**Describe the bug**
Updated to latest and can not log into Apple

**To Reproduce**
See screenshot

**Expected behavior**
Logged in.

**Screenshots**

**Version**
 - OS: 15.1 (24B82)
 - Xcodes: 2.3.0

**Comment by wjiuxing** [comment]
I also encountered the same problem.

**Comment by nolann-dev** [comment]
#630

**Comment by MattKiazyk** [comment]
Closing as duplicate
