### ISSUE TITLE
Can't log in after upgrade to 2.3.0

### ISSUE THREAD

**Issue by Grant-Perry** [XcodesOrg/XcodesApp#635]
After updating to 2.3.0 I no logner can log in. I'm getting error: 

The operation couldn't be completed.
(DecodingError.dataCorrupted (Swift. Deco dingError.Context(codingPath: [],
debugDescription: "The given data was not valid JSON.", underlyingError:
Optional (Error
Domain=NSCocoaErrorDomain
Code=3840 "Unexpected character'‹' around line 1, column 1."
UserInfo={NSDebugDescription=Unexpect
ed character '<' around line 1, column 1.,

Thanks.

Gp.

![screen](https://github.com/user-attachments/assets/4403d0a2-6121-4602-96a0-916bed3c43b9)

**Comment by jzm0720** [comment]
Yes same!!

**Comment by MattKiazyk** [comment]
Please see https://github.com/XcodesOrg/XcodesApp/issues/630
