### ISSUE TITLE
Can't login to my Apple Dev Account

### ISSUE THREAD

**Issue by bielikb** [XcodesOrg/XcodesApp#641]
**Describe the bug**
My credentials that I use to sign into developer.apple.com doesn't work with latest Xcodes v2.4.0 (running on Sequoia 15.1)

**To Reproduce**
Try to log in to the Apple Dev Account

**Expected behavior**
Authorization success

**Screenshots**
FYI, I removed my e-mail from the text field prior taking the screenshot.

<img width="400" alt="Screenshot 2024-10-29 at 07 26 54" src="https://github.com/user-attachments/assets/f9315421-163e-46e0-8ad9-e203febc2c3c">

**Version**
 - OS: Sequoia 15.1
 - Xcodes: 2.4.0

**Comment by xueyaodeai** [comment]
Same issue

**Comment by vincentzchao** [comment]
#630

**Comment by KSemenenko** [comment]
install latest version

**Comment by xueyaodeai** [comment]
> #630
> 
> ## I can sign in now.
> OS: Sonama 14.7 (23H124) Xcodes: 2.4.0 (29)

I know the issue of #630 , but when I update the latest xcodes version, I got this problem.

**Comment by sarvagnan** [comment]
I'm having the same issue. I'm on version 2.4.0 as well

**Comment by MattKiazyk** [comment]
Similar to [fastlane](https://github.com/fastlane/fastlane/issues/26368#issuecomment-2439958035), some people are still having issues. 

Can you try possibly:
- making sure that your email is all lowercase
- reset your password via https://account.apple.com/ and then try again?

**Comment by tpitman** [comment]
I tried logging in very carefully a couple times, then came here.

After reading this I changed my apple password and it works now.

That sucks because I have a lot of apple devices and having to log back into them all it not fun, but at least it worked.

Thank you for the fix.

**Comment by MattKiazyk** [comment]
@tpitman Out of curiosity how old was your password. Another user had 2014 and I'm trying to gauge what the limit is. 

Sorry for the troubles. I wish Apple just provided a simpler way

**Comment by tpitman** [comment]
I didn't look before changing it, but many years. Probably before 2014, so I don't think any newer.

**Comment by sarvagnan** [comment]
Thank you for the fix. Changing the password worked for me too. My old one was from 2013.

**Comment by tdkn** [comment]
I successfully logged in by updating the password that was last changed in 2013.
It doesn't seem to be a problem with Xcodes.app itself.

**Comment by sebsto** [comment]
Apple switched to SRP for authentication.  With SRP, the server has no copy of your password. Instead, a salt (s) and a verifier (v) are computed at registration or change password time. The client will only send s, v, and the username to the server. The server will store s and v.

It means the server needs to be SRP-enabled when you register or change your password to allow the later authentication to work.

With password that are 10+ years old, it is very likely that Apple did not enabled SRP on their side at the time, hence authentication failing now (the server has no s and no v for your password) 

Apple web apps (such as developers.apple.com) kind of detect that and fall back to a less secure, traditional, username + password scheme.

Fastlane, Xcodes and xcodeinstall all support SRP-only authentication as of now.

**Comment by awBSH** [comment]
Changing the PW also solved for me the issue. Thanks for the hint 👍

**Comment by 343max** [comment]
I had the same issue, changing the password fixed it. My old password was from 2012.

**Comment by MattKiazyk** [comment]
I've created a pinned locked issue https://github.com/XcodesOrg/XcodesApp/issues/644 so going to close this issue. Hopefully people will see that pinned issue and resolve before creating a new issue :) 

Thanks everybody. I did see somebody had a 3 year old password only with the same issue, but changing also resolved it.

**Comment by AlexProskurkin** [comment]
I changed my Apple dev password but I keep getting the same issue. 
![image](https://github.com/user-attachments/assets/d379b2dd-b300-4974-8738-2152a3953c0c)

Mac OS: 12.7.6
Xcodes: 1.10.0

**Comment by sebsto** [comment]
@AlexProskurkin It's not the same issue. Your error message is `The given data was not valid JSON` 
This is not the issue we're talking about in this thread. I would suggest to open another issue

**Comment by awBSH** [comment]
@AlexProskurkin this is fixed with [Xcodes 2.4.0](https://github.com/XcodesOrg/XcodesApp/releases/tag/v2.4.0b29)
You are still using Xcode 1.10.0 and need to update.

**Comment by sebsto** [comment]
Thank you @MattKiazyk 

@kabiroberai Do we have an expected PBKDF2 value for both `s2k` and `s2k_fo` ? 
It would be worth adding a unit test for this.
https://github.com/XcodesOrg/XcodesApp/commit/7b154501b6571bcdb339f8fb399d36b7d3635917

**Comment by xueyaodeai** [comment]
> For those users still getting the invalid username/password on Xcodes 2.4.0 - could you please try updating to 2.4.1 and let me know if that fixes your issue

Thanks @MattKiazyk , updating to Xcodes 2.4.1 works for me.

**Comment by kabiroberai** [comment]
> Do we have an expected PBKDF2 value for both s2k and s2k_fo ?

@sebsto I'm a bit hesitant to include a real network capture of my own if that's what you mean, but I think it should be easy to mock the flow to a greater extent than we already do in `AppStateUpdateTests.testSIRP`, so that the PBKDF2 derivation logic is also tested. Not sure I have the bandwidth right now but happy to help answer questions surrounding this; I spent a lot of time reverse engineering this a few years ago when Apple started to require SRP for GrandSlam auth.

**Comment by sebsto** [comment]
@kabiroberai I understand your hesitation (although SRP is designed for that, the client keys are unique for each transaction).

But I was not thinking about that, I was thinking about just sharing data for the PBKDF2 part for `s2k_fo` authentication.  The test you mentioned only test `s2k`
