### ISSUE TITLE
Could not login with iCloud account in Xcodes.

### ISSUE THREAD

**Issue by churchbeamnetherlands** [XcodesOrg/XcodesApp#651]
**Describe the bug**
Logging in with my iCloud account on Xcode's gives this error. Using another valid account gives the same response.

**To Reproduce**
Open Xcode's 
Click on the avatar icon, next to the settings icon in the default ui window.
Fill in username and password. 

**Expected behavior**
Get error.

**Screenshots**
<img width="366" alt="Scherm­afbeelding 2024-11-05 om 12 17 18" src="https://github.com/user-attachments/assets/d39168c4-f355-418d-9a65-9cc5d88a6e25">

**Version**
 - OS: Sonoma Versie 14.7 (23H124)
 - Xcodes: 2.0.2 (23)

**Comment by nikolov9996** [comment]
Hi, you will need to update it to 2.4.1
There is something new in the apple login logic

**Comment by churchbeamnetherlands** [comment]
This works. Ty.
