### ISSUE TITLE
Empty list of Xcodes

### ISSUE THREAD

**Issue by StarWars** [XcodesOrg/XcodesApp#659]
**Describe the bug**
The list of Xcodes is never presented. Refreshing the list does not help.
I have confirmed that cache JSON file contains a list of Xcodes.

**To Reproduce**
Launch the 2.4.1 (30) version of the app, tap "refresh" button.

**Expected behavior**
The list should be filled with the content of the JSON file available in cache.

**Screenshots**
![image](https://github.com/user-attachments/assets/a568854f-8fe7-4ffa-b92d-d7d91178cfad)

**Version**
 - OS: Sequoia 15.1
 - Xcodes: 2.4.1 (30)

**Comment by MattKiazyk** [comment]
Tap the `>>` arrow - are you filtering on anything? 

Or increase the size of the left side to see
