### ISSUE TITLE
Logging in responds with `keynotFound salt` error

### ISSUE THREAD

**Issue by MattKiazyk** [XcodesOrg/XcodesApp#660]
**Describe the bug**
When logging in - xcodes returns `keynotFound salt` error 

![USsBTPrm1SrCeM6wryGfQagN](https://github.com/user-attachments/assets/e9e39d46-8ca4-460c-be1c-68fe4dff128d)

I'm assuming Apple changed login again.. which make me sad.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**
 - OS: 15.0
 - Xcodes: 2.4.1 (30)

**Comment by keremersu35** [comment]
Same here

**Comment by MattKiazyk** [comment]
I'm having troubles with ASC today so I'm hoping it's a temporary Apple issue.

**Comment by MattKiazyk** [comment]
Tried again and it seems to be working now - @keremersu35 how is it on your end?

**Comment by keremersu35** [comment]
Looks good on my end as well, thanks

**Comment by pauliusguzas** [comment]
Same bug on 2.4.1

**Comment by jkyoutsey** [comment]
Same issue on 2.4.2

**Comment by kraenhansen** [comment]
I'm hitting this with Xcodes v3.0.2 and an app-specific password 🤔 If [this is not yet supported](https://github.com/XcodesOrg/XcodesApp/issues/431), that would be good to surface front and center when this particular error surfaces.
