### ISSUE TITLE
Can't install any xcode versions

### ISSUE THREAD

**Issue by pmhk2156** [XcodesOrg/XcodesApp#671]
I used the command to install Xcodes:
`brew install --cask xcodes`
Xcodes version: 2.4.1, macOS version: Sonoma 14.6.1 (23G93).

I logged into my Apple account and tried to install several versions of Xcode, but all installations failed. I received the error message: "If you continue to have problems, please submit a bug report in the Help menu."

**Comment by oddarchii** [comment]
I have the same problem .....Help me please!!!!

**Comment by pmhk2156** [comment]
The problem was resolved. I found this issue , logged in with my Apple account, accepted the terms of the developer agreement, and then tried installing again. As a result, the installation was successful.
https://github.com/XcodesOrg/XcodesApp/issues/658#issuecomment-2488953019
